name: entry_page
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.3
  path_provider: ^2.0.0
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_splash_page.png
    - assets/images/bel_flag.png
    - assets/images/usa_flag.png
    - assets/images/rus_flag.png
    - assets/icon/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false